//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CICDataBase.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Record
    {
        public int Id { get; set; }
        [DisplayName("Army Number")]
        [Required(ErrorMessage = "Army Number is required")]
        public string ArmyNumber { get; set; }
        [Required(ErrorMessage = "Rank is required")]
        public string Rank { get; set; }
        [DisplayName("First name")]
        [Required(ErrorMessage = "First Name is required")]
        public string FirstName { get; set; }
        [DisplayName("Middle Name")]
        [Required(ErrorMessage = "Middle Name is required")]
        public string MiddleName { get; set; }
        [DisplayName("Last Name")]
        [Required(ErrorMessage = "Last Name is required")]
        public string LastName { get; set; }
        [DisplayName("Date of Birth")]
        [Required(ErrorMessage = "Date Of Birth is required")]
        public System.DateTime DOB { get; set; }
        [DisplayName("Date of Retirement")]
        [Required(ErrorMessage = "ROD is required")]
        public System.DateTime ROD { get; set; }
        [DisplayName("State of Origin")]
        [Required(ErrorMessage = "State of Origin is required")]
        public string StateOfOrigin { get; set; }
        [DisplayName("Phone Number")]
        [Required(ErrorMessage = "Phone Number is required")]
        public short phoneNumber { get; set; }
    }
}
